### ISSUE TITLE
Problem in python packages while Project Setup

### ISSUE THREAD

**Issue by promehul** [HelikarLab/candis#163] opened 2019-02-16 05:19 UTC
#### Expected Behaviour
While using pip install -r requirements.txt all packages should get installed 

#### Actual Behaviour
Some packages were not getting installed because the version mentioned was outdated or had been depreciated.
#### Steps to Reproduce:
* All dependencies and packages needs to be updated

NOTE: Add a GIF/Screenshot if required.

**Comment by achillesrasquinha** [comment] 2019-02-17 22:06
What are the dependency conflicts you're facing? What branch are you trying to use?

**Comment by akram-mohammed** [comment] 2019-02-18 01:27
Harshit, Thanks for creating a ticket.

Sent from Mail for Windows 10

From: harshit khetan
Sent: Friday, February 15, 2019 11:19 PM
To: HelikarLab/candis
Cc: Subscribed
Subject: [HelikarLab/candis] Problem in python packages while Project Setup(#163)

Expected Behaviour
While using pip install -r requirements.txt all packaes should get installed
Actual Behaviour
Some packages were not getting installed because the versin mentioned was outdated or had been depreciated.
Steps to Reproduce:
• 
NOTE: Add a GIF/Screenshot if required.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by promehul** [comment] 2019-02-19 11:32
While setting it up , as I was installing the packages server didn't run because many python packages failed to install because their versions didnt match. I was on branch develop

**Comment by achillesrasquinha** [comment] 2019-02-25 03:23
@promehul what are the packages that failed to install?

**Comment by promehul** [comment] 2019-02-27 16:00
Many packages like ipython,javabridge,rpy2,etc

**Comment by achillesrasquinha** [comment] 2019-02-27 16:51
@promehul A traceback would be helpful. Thanks!

**Comment by promehul** [comment] 2019-02-28 14:44
![screenshot from 2019-03-01 14-58-13](https://user-images.githubusercontent.com/32803738/53574348-71632680-3b95-11e9-90dd-044f4bc4dc12.png)
![screenshot from 2019-03-01 14-58-17](https://user-images.githubusercontent.com/32803738/53574377-7d4ee880-3b95-11e9-99ad-7a3c97b492d1.png)

**Comment by majumderS** [comment] 2019-02-28 18:16
Hi. Pygraphviz is an interface for graphviz package. 
1) Try installing graphviz first.
sudo apt-get install graphviz libgraphviz-dev pkg-config
2) Then pygraphviz
Run pip install pygraphviz
Hope that helps!

**Comment by promehul** [comment] 2019-02-28 18:23
![screenshot from 2019-03-01 18-37-55](https://user-images.githubusercontent.com/32803738/53588878-f65d3880-3bb3-11e9-800d-679464cacf47.png)
![screenshot from 2019-03-01 18-38-03](https://user-images.githubusercontent.com/32803738/53588884-fb21ec80-3bb3-11e9-819e-cf8b9905dde5.png)

**Comment by majumderS** [comment] 2019-02-28 18:29
@promehul do you have java installed in your ubuntu machine? It seems like a java issue.

**Comment by promehul** [comment] 2019-02-28 18:37
its installed.. i think its the issue with the path.. What path did u set in for java?

**Comment by majumderS** [comment] 2019-02-28 18:42
/usr/lib/jvm/java-8-oracle

**Comment by achillesrasquinha** [comment] 2019-03-07 18:36
The [Dockerfile](https://github.com/HelikarLab/candis/blob/develop/Dockerfile) is a good starting point to overcome dependencies.

**Comment by achillesrasquinha** [comment] 2019-03-07 18:36
I'm closing this. A very system related issue IMHO. Feel free to reopen if that not being the case.

**Closed as completed by achillesrasquinha** 2019-03-07 18:36 UTC
